### ISSUE TITLE
USE_IAM not working

### ISSUE THREAD

**Issue by danielbeicht** [cloudlena/s3manager#21]
Hi,
when I try using the USE_IAM-environment variable using docker I get the error message "please provide ACCESS_KEY_ID". Tested with:

```
version: '3.4'
services:
  s3manager:
    image: cloudlena/s3manager
    environment:
      - USE_IAM=true
    ports:
      - 80:8080
 ```

and

`docker run -p 80:8080 -e 'USE_IAM=true' cloudlena/s3manager`
