### ISSUE TITLE
`USE_SSL=false` does not work

### ISSUE THREAD

**Issue by MickL** [cloudlena/s3manager#8]
> error listing buckets: Get "https://localhost:4572/": dial tcp 127.0.0.1:4572: connect: connection refused

With:

```
  s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8002:8080
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - REGION=eu-central-1
      - ENDPOINT=localhost:4572
      - PORT=8080
      - USE_SSL=false
```

**Comment by MickL** [comment]
@mastertinner Could you take a look maybe? :)

**Comment by mastertinner** [comment]
@MickL, can you try the `docker-compose.yml` example with `docker-compose up`? That one works for me with `USE_SSL=false`...

**Comment by MickL** [comment]
I think it works, I replaced localhost with the name of the other image (localstack) but now I get:

> s3-manager_1        | 2020/06/17 12:48:34 GET   /buckets        29.8724ms
> s3-manager_1        | 2020/06/17 12:48:34 error parsing template files: open web/template/layout.html.tmpl: no such file or directory


```
localstack:
    image: localstack/localstack
    ports:
      - 4569:4569
      - 4572:4572
      - 8000:8080
    environment:
      - SERVICES=dynamodb:4569,s3:4572
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION:eu-central-1
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
  s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8002:8080
    depends_on:
      - localstack
    links:
      - localstack
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - REGION=eu-central-1
      - ENDPOINT=localstack:4572
      - PORT=8080
      - USE_SSL=false
```
